### ISSUE TITLE
CRC16 Validation - MPM

### ISSUE THREAD

**Issue by JulioRuiOliveira** [mvallim/emv-qrcode#19]
Boa noite, Marcos.

Houve a remoção da validação do CRC16 (presença do campo e cálculo) no QR Code (MPM) ?
Se sim, a lib proporciona alguma outra forma de efetuar essa validação?

Edit: Acabei de encontrar o CRC16 Validator na lib. Perdão, hehe

**Comment by mvallim** [comment]
@JulioRuiOliveira 

Sem problemas, consegue ajudar a gente com um start e um follow?

Abraços,
