### ISSUE TITLE
CPM

### ISSUE THREAD

**Issue by sloopsight** [mvallim/emv-qrcode#20]
Hi,
I am trying just wondering how I can read my credit card data to generate EMV QR code.  
Also for QR Code transaction where I have to include amount in example it is not clear.
Any help will be appreciated.

**Comment by mvallim** [comment]
Hi @sloopsight,

This whole specification of how the parties interact is specified in the [Consumer-Presented Mode document](https://github.com/mvallim/emv-qrcode/blob/master/docs/EMVCo-Consumer-Presented-QR-Specification-v1-1.pdf).

In the examples presented, it is shown how to encode and decode information, remembering that it is a library that abstracts the process of encoding and decoding information.

The process in which the consumer generates the QR Code, the QR Code Reader forwards the information to the POI and at that moment more information is added to the QR Code that is sent to the Merchant through the entire bank flow until its return when the transaction is completed.

This can be seen on page. 11, 12, and 13 with an illustrative image of the fluxon, on the following pages it is detailed how each participant acts at each point.

If you have any more questions let me know.

Thanks,

**Comment by sloopsight** [comment]
I want to customer present mode from scratch any idea from where I can start.

**Comment by mvallim** [comment]
Hi @sloopsight,

```text
            +--------------------------------------------------------------------+
            |                             Consumer                               |
            |  +------------+    +-----------------+    +---------------------+  |
            |  | create CPM | -> | encode toBase64 | -> | create image QRCode |  |
            |  +------------+    +-----------------+    +---------------------+  |
            +-------------------------------+------------------------------------+
                                            |
                                +-----------+-----------+
                                |  QRCode Image Reader  |
                                |   +--------------+    |
                                |   | decode image |    |
                                |   +--------------+    |
                                +-----------+-----------+
                                            |
+-------------------------------------------+------------------------------------------+
|                                          POI                                         |
|   +------------+    +--------------+    +------------------+    +-----------------+  |
|   | decode CPM | -> | validate CPM | -> | add informations | -> | encode toBase64 |  |
|   +------------+    +--------------+    +------------------+    +-----------------+  |
+-------------------------------------------+------------------------------------------+
                                            |
            +-------------------------------+-----------------------------+
            |                            Merchant                         |
            | +------------+    +--------------+    +------------------+  |
            | | decode CPM | -> | validate CPM | -> | add informations |  |
            | +------------+    +--------------+    +------------------+  |
            +-------------------------------+-----------------------------+
                                            |
                                       +----+-----+
                                       | Acquirer |
                                       +----+-----+
                                            |
                                   +--------+--------+
                                   | Payment Network |
                                   +--------+--------+
                                            |
                                        +---+----+
                                        | Issuer |
                                        +--------+
```

**Comment by sloopsight** [comment]
Thank you  mvallim,
Can u recommend some study material from where I can start 
EMV Book 3 or 4 ?
You have written program for encoder decoder
Now How I can read card from mobile phone  how I can get access to Track 2 equivalent data from card.
Do I have code POI  or POI is a standard device available in market.
I am new to this device based transaction I might sound kiddish but If you explain or guide me would be great help.

**Comment by mvallim** [comment]
> Thank you mvallim,
> Can u recommend some study material from where I can start
> EMV Book 3 or 4 ?
> You have written program for encoder decoder
> Now How I can read card from mobile phone how I can get access to Track 2 equivalent data from card.
> Do I have code POI or POI is a standard device available in market.
> I am new to this device based transaction I might sound kiddish but If you explain or guide me would be great help.

Hi @sloopsight,

No problem, what you need in this case is the NFC (Near Field Communication) specification, from that point on you will be able to read the chip information and set up a CPM using that information.

Initially, there is some information here:
https://en.wikipedia.org/wiki/Near-field_communication
https://en.wikipedia.org/wiki/Contactless_smart_card

This can better elucidate what you want to do.

Remembering that EMV and NFC are complementary technologies that allow secure contactless payments.

Thanks,

**Comment by sloopsight** [comment]
Hi @mvallim 
What about POI is this a standard device available in market or we have to build it.

**Comment by mvallim** [comment]
> Hi @mvallim
> What about POI is this a standard device available in market or we have to build it.

Hi @sloopsight,

In the specification he makes it clear, page 11,12 and 13 [here]()

* **QR Code Reader** - Scans the QR Code, decodes the QR Code and sends the data recovered to the POI System. This data constitutes the base64 encoded QR Code Payload.
* **POI Application** - The application developed by the POI vendor to process the base64 encoded QR Code payload defined in this specification. Its functions include base64 decoding, parsing the data, checking content and format and transaction processing.

Thanks,

**Comment by subhanshu-shukla** [comment]
Who is poi vendor here company like pinelabs and ingenico we can develop it using andoid app?

**Comment by mvallim** [comment]
> Who is poi vendor here company like pinelabs and ingenico we can develop it using andoid app?

_"A point of interaction (POI) is a (hardware and/or software) component in point of sale equipment (e.g. a magnetic card reader) that enables a consumer to use a credit card to make a purchase at a retailer. The point of sale terminal might be attended or unattended.

The new generation of POI systems will be designed to allow devices other than credit cards to be used to make payments (e.g. mobile phones or PDAs), provided that the same high level of security is ensured by the equipment."_

* **Mobile application/wallet** - A consumer-facing user interface (UI) application provided by the issuer, merchant, or a third-party and provisioned to the consumer’s mobile device. It includes the functionality to encode the payment credentials based on this specification, and then displays the resulting QR Code.
* **QR Code Payload** - The payload, consisting of payment token credentials and other 
data based on this specification, converted to base64 and encoded in a QR Code.

**Comment by mvallim** [comment]
> Who is poi vendor here company like pinelabs and ingenico we can develop it using andoid app?

*"A point of interaction (POI) is a (hardware and/or software) component in point of sale equipment (e.g. a magnetic card reader) that enables a consumer to use a credit card to make a purchase at a retailer. The point of sale terminal might be attended or unattended.

The new generation of POI systems will be designed to allow devices other than credit cards to be used to make payments (e.g. mobile phones or PDAs), provided that the same high level of security is ensured by the equipment."*

**Comment by mvallim** [comment]
Closing this issue for being without activity.
